apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilient-training-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resilient-training-operator
  template:
    metadata:
      labels:
        app: resilient-training-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - -alsologtostderr
        image: kuizhiqing/resilient-training-operator:latest
        name: resilient-training-operator
      serviceAccountName: resilient-training-operator
