apiVersion: apps/v1
kind: Deployment
metadata:
  name: launch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launch-operator
  template:
    metadata:
      labels:
        app: launch-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - -alsologtostderr
        image: mpioperator/mpi-operator:latest
        name: launch-operator
      serviceAccountName: launch-operator
