# coding: utf-8

"""
    resilientjob

    Python SDK for Resilient Training Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import resilientjob
from resilientjob.models.v2beta1_resilient_job import V2beta1ResilientJob  # noqa: E501
from resilientjob.rest import ApiException

class TestV2beta1ResilientJob(unittest.TestCase):
    """V2beta1ResilientJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V2beta1ResilientJob
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = resilientjob.models.v2beta1_resilient_job.V2beta1ResilientJob()  # noqa: E501
        if include_optional :
            return V2beta1ResilientJob(
                api_version = '', 
                kind = '', 
                metadata = None, 
                spec = resilientjob.models.v2beta1/resilient_job_spec.v2beta1.ResilientJobSpec(
                    mpi_implementation = '', 
                    mpi_replica_specs = {
                        'key' : resilientjob.models.v1/replica_spec.v1.ReplicaSpec(
                            replicas = 56, 
                            restart_policy = '', 
                            template = None, )
                        }, 
                    run_policy = resilientjob.models.v1/run_policy.v1.RunPolicy(
                        active_deadline_seconds = 56, 
                        backoff_limit = 56, 
                        clean_pod_policy = '', 
                        scheduling_policy = resilientjob.models.v1/scheduling_policy.v1.SchedulingPolicy(
                            min_available = 56, 
                            min_resources = {
                                'key' : None
                                }, 
                            priority_class = '', 
                            queue = '', 
                            schedule_timeout_seconds = 56, ), 
                        ttl_seconds_after_finished = 56, ), 
                    slots_per_worker = 56, 
                    ssh_auth_mount_path = '', ), 
                status = resilientjob.models.v1/job_status.v1.JobStatus(
                    completion_time = None, 
                    conditions = [
                        resilientjob.models.v1/job_condition.v1.JobCondition(
                            last_transition_time = None, 
                            last_update_time = None, 
                            message = '', 
                            reason = '', 
                            status = '', 
                            type = '', )
                        ], 
                    last_reconcile_time = None, 
                    replica_statuses = {
                        'key' : resilientjob.models.v1/replica_status.v1.ReplicaStatus(
                            active = 56, 
                            failed = 56, 
                            label_selector = None, 
                            selector = '', 
                            succeeded = 56, )
                        }, 
                    start_time = None, )
            )
        else :
            return V2beta1ResilientJob(
        )

    def testV2beta1ResilientJob(self):
        """Test V2beta1ResilientJob"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
