# coding: utf-8

"""
    resilientjob

    Python SDK for Resilient Training Operator  # noqa: E501

    The version of the OpenAPI document: v2beta1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import resilientjob
from resilientjob.models.v1_job_condition import V1JobCondition  # noqa: E501
from resilientjob.rest import ApiException

class TestV1JobCondition(unittest.TestCase):
    """V1JobCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1JobCondition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = resilientjob.models.v1_job_condition.V1JobCondition()  # noqa: E501
        if include_optional :
            return V1JobCondition(
                last_transition_time = None, 
                last_update_time = None, 
                message = '', 
                reason = '', 
                status = '', 
                type = ''
            )
        else :
            return V1JobCondition(
                status = '',
                type = '',
        )

    def testV1JobCondition(self):
        """Test V1JobCondition"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
