// Copyright 2023 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2beta1 "github.com/kuizhiqing/resilient-training-operator/pkg/apis/kubeflow/v2beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResilientJobs implements ResilientJobInterface
type FakeResilientJobs struct {
	Fake *FakeKubeflowV2beta1
	ns   string
}

var resilientjobsResource = schema.GroupVersionResource{Group: "kubeflow.org", Version: "v2beta1", Resource: "resilientjobs"}

var resilientjobsKind = schema.GroupVersionKind{Group: "kubeflow.org", Version: "v2beta1", Kind: "ResilientJob"}

// Get takes name of the mPIJob, and returns the corresponding mPIJob object, and an error if there is any.
func (c *FakeResilientJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.ResilientJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resilientjobsResource, c.ns, name), &v2beta1.ResilientJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2beta1.ResilientJob), err
}

// List takes label and field selectors, and returns the list of ResilientJobs that match those selectors.
func (c *FakeResilientJobs) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.ResilientJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resilientjobsResource, resilientjobsKind, c.ns, opts), &v2beta1.ResilientJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2beta1.ResilientJobList{ListMeta: obj.(*v2beta1.ResilientJobList).ListMeta}
	for _, item := range obj.(*v2beta1.ResilientJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mPIJobs.
func (c *FakeResilientJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resilientjobsResource, c.ns, opts))

}

// Create takes the representation of a mPIJob and creates it.  Returns the server's representation of the mPIJob, and an error, if there is any.
func (c *FakeResilientJobs) Create(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.CreateOptions) (result *v2beta1.ResilientJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resilientjobsResource, c.ns, mPIJob), &v2beta1.ResilientJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2beta1.ResilientJob), err
}

// Update takes the representation of a mPIJob and updates it. Returns the server's representation of the mPIJob, and an error, if there is any.
func (c *FakeResilientJobs) Update(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (result *v2beta1.ResilientJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resilientjobsResource, c.ns, mPIJob), &v2beta1.ResilientJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2beta1.ResilientJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResilientJobs) UpdateStatus(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (*v2beta1.ResilientJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resilientjobsResource, "status", c.ns, mPIJob), &v2beta1.ResilientJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2beta1.ResilientJob), err
}

// Delete takes name of the mPIJob and deletes it. Returns an error if one occurs.
func (c *FakeResilientJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(resilientjobsResource, c.ns, name, opts), &v2beta1.ResilientJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResilientJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resilientjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2beta1.ResilientJobList{})
	return err
}

// Patch applies the patch and returns the patched mPIJob.
func (c *FakeResilientJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.ResilientJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resilientjobsResource, c.ns, name, pt, data, subresources...), &v2beta1.ResilientJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2beta1.ResilientJob), err
}
