apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
namespace: resilient-training-operator
commonLabels:
  kustomize.component: resilient-training-operator
  app: resilient-training-operator
  app.kubernetes.io/name: resilient-training-operator
  app.kubernetes.io/component: resilientjob
images:
- name: kuizhiqing/resilient-training-operator
  newName: kuizhiqing/resilient-training-operator
  newTag: master
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: resilient-training-operator
    path: ./patch.yaml
