// Copyright 2023 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	"context"
	"time"

	v2beta1 "github.com/kuizhiqing/resilient-training-operator/pkg/apis/kubeflow/v2beta1"
	scheme "github.com/kuizhiqing/resilient-training-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResilientJobsGetter has a method to return a ResilientJobInterface.
// A group's client should implement this interface.
type ResilientJobsGetter interface {
	ResilientJobs(namespace string) ResilientJobInterface
}

// ResilientJobInterface has methods to work with ResilientJob resources.
type ResilientJobInterface interface {
	Create(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.CreateOptions) (*v2beta1.ResilientJob, error)
	Update(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (*v2beta1.ResilientJob, error)
	UpdateStatus(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (*v2beta1.ResilientJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2beta1.ResilientJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2beta1.ResilientJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.ResilientJob, err error)
	ResilientJobExpansion
}

// mPIJobs implements ResilientJobInterface
type mPIJobs struct {
	client rest.Interface
	ns     string
}

// newResilientJobs returns a ResilientJobs
func newResilientJobs(c *KubeflowV2beta1Client, namespace string) *mPIJobs {
	return &mPIJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mPIJob, and returns the corresponding mPIJob object, and an error if there is any.
func (c *mPIJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.ResilientJob, err error) {
	result = &v2beta1.ResilientJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resilientjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResilientJobs that match those selectors.
func (c *mPIJobs) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.ResilientJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2beta1.ResilientJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resilientjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mPIJobs.
func (c *mPIJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resilientjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mPIJob and creates it.  Returns the server's representation of the mPIJob, and an error, if there is any.
func (c *mPIJobs) Create(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.CreateOptions) (result *v2beta1.ResilientJob, err error) {
	result = &v2beta1.ResilientJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resilientjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mPIJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mPIJob and updates it. Returns the server's representation of the mPIJob, and an error, if there is any.
func (c *mPIJobs) Update(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (result *v2beta1.ResilientJob, err error) {
	result = &v2beta1.ResilientJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resilientjobs").
		Name(mPIJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mPIJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mPIJobs) UpdateStatus(ctx context.Context, mPIJob *v2beta1.ResilientJob, opts v1.UpdateOptions) (result *v2beta1.ResilientJob, err error) {
	result = &v2beta1.ResilientJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resilientjobs").
		Name(mPIJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mPIJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mPIJob and deletes it. Returns an error if one occurs.
func (c *mPIJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resilientjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mPIJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resilientjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mPIJob.
func (c *mPIJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.ResilientJob, err error) {
	result = &v2beta1.ResilientJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resilientjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
