// Copyright 2023 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	v2beta1 "github.com/kuizhiqing/resilient-training-operator/pkg/apis/kubeflow/v2beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ResilientJobLister helps list ResilientJobs.
// All objects returned here must be treated as read-only.
type ResilientJobLister interface {
	// List lists all ResilientJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.ResilientJob, err error)
	// ResilientJobs returns an object that can list and get ResilientJobs.
	ResilientJobs(namespace string) ResilientJobNamespaceLister
	ResilientJobListerExpansion
}

// mPIJobLister implements the ResilientJobLister interface.
type mPIJobLister struct {
	indexer cache.Indexer
}

// NewResilientJobLister returns a new ResilientJobLister.
func NewResilientJobLister(indexer cache.Indexer) ResilientJobLister {
	return &mPIJobLister{indexer: indexer}
}

// List lists all ResilientJobs in the indexer.
func (s *mPIJobLister) List(selector labels.Selector) (ret []*v2beta1.ResilientJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2beta1.ResilientJob))
	})
	return ret, err
}

// ResilientJobs returns an object that can list and get ResilientJobs.
func (s *mPIJobLister) ResilientJobs(namespace string) ResilientJobNamespaceLister {
	return mPIJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ResilientJobNamespaceLister helps list and get ResilientJobs.
// All objects returned here must be treated as read-only.
type ResilientJobNamespaceLister interface {
	// List lists all ResilientJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.ResilientJob, err error)
	// Get retrieves the ResilientJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2beta1.ResilientJob, error)
	ResilientJobNamespaceListerExpansion
}

// mPIJobNamespaceLister implements the ResilientJobNamespaceLister
// interface.
type mPIJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ResilientJobs in the indexer for a given namespace.
func (s mPIJobNamespaceLister) List(selector labels.Selector) (ret []*v2beta1.ResilientJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2beta1.ResilientJob))
	})
	return ret, err
}

// Get retrieves the ResilientJob from the indexer for a given namespace and name.
func (s mPIJobNamespaceLister) Get(name string) (*v2beta1.ResilientJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2beta1.Resource("resilientjob"), name)
	}
	return obj.(*v2beta1.ResilientJob), nil
}
